### ISSUE TITLE
Login & processing issues

### ISSUE THREAD

**Issue by chauffer** [asciinema/asciinema-server#295]
Hey there, I'm trying to setup asciinema, I copied most of the docker-compose file to set this up on Rancher[0]. 

I'm encountering the following issues:
- `/login/new` redirects me to `/not-gonna-happen`, showing `The page you were looking for doesn't exist.`
- `/a/1`, the demo recording, says `This recording is being pre-processed at the moment. It will open automatically in a few seconds.` even after hours of uptime
- `/docs` is also a 404
I have run `setup` initially, although the webserver was already running at that time.

[0]
```
version: '2'
volumes:
  aciinema-redis-data:
    external: true
    driver: rancher-nfs
  asciinema-postgres-data:
    external: true
    driver: rancher-nfs
  asciinema-asciinema-volumes-cache:
    external: true
    driver: rancher-nfs
  asciinema-asciinema-uploads:
    external: true
    driver: rancher-nfs
  asciinema-asciinema-tmp:
    external: true
    driver: rancher-nfs
  asciinema-asciinema-log:
    external: true
    driver: rancher-nfs
services:
  asciinema:
    image: asciinema/asciinema-server:develop
    environment:
      DATABASE_URL: ...
      REDIS_URL: ...
      SMTP_FROM_ADDRESS: ...
      SECRET_KEY_BASE: ...
      URL_SCHEME: https
      URL_HOST: ...
    stdin_open: true
    volumes:
    - asciinema-asciinema-uploads:/uploads
    - asciinema-asciinema-log:/app/log
    - asciinema-asciinema-tmp:/tmp
    - asciinema-asciinema-volumes-cache:/cache
    tty: true
    labels:
      io.rancher.container.pull_image: always
  redis:
    image: redis:alpine
    stdin_open: true
    volumes:
    - aciinema-redis-data:/data
    tty: true
    labels:
      io.rancher.container.pull_image: always
  postgres:
    image: postgres:alpine
    stdin_open: true
    volumes:
    - asciinema-postgres-data:/var/lib/postgresql/data
    tty: true
    labels:
      io.rancher.container.pull_image: always
```
