### ISSUE TITLE
Home page displays: This recording is being pre-processed at the moment

### ISSUE THREAD

**Issue by dippynark** [asciinema/asciinema-server#310]
I am trying to run asciinema-server on Kubernetes and am running into issues when trying to render my submitted casts. Loading up the home page shows the following message where the default cast should appear:

```
This recording is being pre-processed at the moment. It will open automatically in a few seconds.

Feel free to contact support@asciinema.org if it takes longer.
```

All other features seems to be working however. I can login and submit casts which appear in my user account and screenshots of these casts are being displayed correctly. However, when trying to play the cast, I see the same message above.

Things that may be of interest:
- The ExqUI is showing casts being processed successfully after submitting
- No components of asciinema-server are showing any obvious error messages from looking at what the containers are printing to stdout/stderr

Is there a good place to look to try and debug this further?

Environment:
- asciinema-server image: `asciinema-server:latest`
- postgres image: `postgres:10.3`
- redis image: `microbox/redis:2.6.17`
- smtp image: `namshi/smtp:latest`
- nginx image: `nginx:alpine`
- Kubernetes version: 1.9.3

**Comment by carlosdagos** [comment]
Having the same issue here. Haven't been able to find a solution yet.

**Comment by carlosdagos** [comment]
As an update, I managed to get it working by simply restarting the whole thing. I know that's not too helpful though in terms of narrowing down what could be going wrong :)

**Comment by carlosdagos** [comment]
Potentially, this issue could be related: https://github.com/asciinema/asciinema-server/issues/295

**Comment by dippynark** [comment]
I'm still seeing the same behaviour - would be interested to see what you have in your `asciinema-config` configmap as I am only using a secret (containing the `SECRET_KEY_BASE` and my gmail password)

**Comment by dippynark** [comment]
So the environment for my `asciinema-server` containers looks like:
```
        env:
        - name: URL_SCHEME
          value: "https"
        - name: URL_HOST
          value: "asciinema.lukeaddison.co.uk"
        - name: URL_PORT
          value: "443"
        - name: SECRET_KEY_BASE
          valueFrom: 
            secretKeyRef:
              name: "asciinema"
              key: secret-key-base
        - name: HOME_ASCIICAST_ID
          value: "1"
```

**Comment by dippynark** [comment]
So the environment for my `asciinema-server` containers looks like:
```
        env:
        - name: URL_SCHEME
          value: "https"
        - name: URL_HOST
          value: "<my_hostname>"
        - name: URL_PORT
          value: "443"
        - name: SECRET_KEY_BASE
          valueFrom: 
            secretKeyRef:
              name: "asciinema"
              key: secret-key-base
        - name: HOME_ASCIICAST_ID
          value: "1"
```
